# general configuration
url: " "
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/octopus.png"
  # author will appear under the avatar (optional)
  author: "Shweta Prasad"
  # tagline will appear under the title (optional)
  tagline: "Computational Biology. Senior, Ashoka University."
  # <a href='http://shw3ta.github.io/shweta.github.io'>Shweta Prasad</a> 
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "tundra_theraimy"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
